"""
Take a few frames from a vid stack generated by 'make_live_video.py -f'
and concatenate them horizontally.
"""

import pickle
import numpy as np
import cv2
import os.path as osp

PREFIX = "/home/lowell/reward-poisoned-drl/data/attack_figs/delay_poison/"
VID_PKL_FILE = "p25.pkl"
DISP_OUT_FILE = "targ_bottom_poison_failure_deltp25.png"

# SEL_IDXS = (47, 51, 52, 56)  # for targ mid success on delta 2.0
# SEL_IDXS = (159, 163, 164, 168)  # for targ bottom sucess on delta 2.0
# SEL_IDXS = (196, 200, 201, 204)  # for non-target upper field on delta 2.0 --> good agent behavior
SEL_IDXS = (128, 132, 133, 138)  # for targ bottom failure on delta 0.25


with open(osp.join(PREFIX, VID_PKL_FILE), "rb") as f:
    feed = pickle.load(f)

H = feed.shape[1]
frames = [feed[idx] for idx in SEL_IDXS]

for i in range(1, len(SEL_IDXS)):  # add thin white lines between frames to aid in viewing
    frames.insert(2 * i - 1, np.full((H, 1, 3), 255, dtype=np.uint8))

display = np.concatenate(frames, axis=1).squeeze()

display = cv2.cvtColor(display, cv2.COLOR_RGB2BGR)
cv2.imwrite(osp.join(PREFIX, DISP_OUT_FILE), display)
